class_name DungeonGenerationTypes extends RefCounted

enum GenerationLifecycleState {
	RECEIVED,
	VALIDATED,
	GENERATING_LAYOUT,
	VALIDATED_LAYOUT,
	POPULATING_SPAWNS,
	COMMITTED,
	REJECTED
}

const FAILURE_INVALID_REQUEST: String = "INVALID_REQUEST"
const FAILURE_POSITION_OUT_OF_BOUNDS: String = "POSITION_OUT_OF_BOUNDS"
const FAILURE_POSITION_NOT_PLACEABLE: String = "POSITION_NOT_PLACEABLE"
const FAILURE_START_EQUALS_EXIT: String = "START_EQUALS_EXIT"
const FAILURE_LAYOUT_INFEASIBLE: String = "LAYOUT_INFEASIBLE"
const FAILURE_AUTHORITY_VIOLATION: String = "AUTHORITY_VIOLATION"
const FAILURE_SESSION_CONFLICT: String = "SESSION_CONFLICT"

static func failure_codes() -> PackedStringArray:
	return PackedStringArray([
		FAILURE_INVALID_REQUEST,
		FAILURE_POSITION_OUT_OF_BOUNDS,
		FAILURE_POSITION_NOT_PLACEABLE,
		FAILURE_START_EQUALS_EXIT,
		FAILURE_LAYOUT_INFEASIBLE,
		FAILURE_AUTHORITY_VIOLATION,
		FAILURE_SESSION_CONFLICT
	])

static func is_valid_failure_code(error_code: String) -> bool:
	return failure_codes().has(error_code)
